spring.application.name=anjos-bolos-api-email

# Configuração RabbitMQ
spring.rabbitmq.host=rabbitmq-email
spring.rabbitmq.port=5673
spring.rabbitmq.username=myuser
spring.rabbitmq.password=secret

# Fila para Encomendas
broker.encomenda.exchange.name=encomenda.fanout.exchange
broker.encomenda.queue.name=encomenda.queue

# Fila para Backups
broker.backup.exchange.name=backup.fanout.exchange
broker.backup.queue.name=backup.queue

# Configura��o Email Encomendas
spring.encomenda.mail.host=smtp.gmail.com
spring.encomenda.mail.port=587
spring.encomenda.mail.username=lucaslucena310805@gmail.com
spring.encomenda.mail.password=${EMAIL_SECRET}
spring.encomenda.mail.to=gustavo.presilli@sptech.school

# Configura��o Email Backups
spring.backup.mail.host=smtp.gmail.com
spring.backup.mail.port=587
spring.backup.mail.username=backup.anjosbolos@gmail.com
spring.backup.mail.password=${BACKUP_EMAIL_SECRET}
spring.backup.mail.to=someone@email.com

server.port=8081