spring.application.name=bingo
broker.exchange.name=example.fanout.exchange
broker.queue.name=example.queue

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=lucaslucena310805@gmail.com
spring.mail.password=slwg feph fhzd buzv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

